### ISSUE TITLE
Update Text Section

### ISSUE THREAD

**Issue by bliutech** [uclaacm/lactf-website#29]
**Figma Design:**
<img width="751" alt="image" src="https://user-images.githubusercontent.com/67720812/197366126-6a36251f-d031-456a-a16d-53cb97bf0d5c.png">

**Current Site:**
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/67720812/197366133-5737ac97-930d-4178-9885-6681fa9adff4.png">

Update the current site to conform to the Figma's design for the middle text section.
- [x] export SVGs from Figma
- [x] update text content
- [x] most likely use flexbox to allow for dynamic and accurate centering
- [x] ensure that it confirms on mobile views
- [x] add onhover animation for SVGs to make it pop :)

**Comment by burturt** [comment]
I may work on this, but first working on fixing the fact that the about section adds a horizontal scrollbar on the page

**Comment by burturt** [comment]
Finally exported figma images with the diamond in the center for all of them: [LA CTF About images.zip](https://github.com/uclaacm/lactf-website/files/9857742/LA.CTF.About.images.zip)
One of the icons is not an svg so I don't really see the point in using svg especially since the icons won't be that big anyway

**Comment by bliutech** [comment]
@burturt might be fixable in the Figma directly so we can export an group so we can just embed that in. Also possible to implement diamonds in CSS. I think there's an example in https://github.com/uclaacm/cyber-platform somewhere...

**Comment by burturt** [comment]
I got everything working EXCEPT the drop shadow - next.js seems to wrap images inside of a span, which has a `overflow: hidden` property causing issues. Probably will need to undo my image vertical cropping to get it to work.
![Screen Shot 2022-10-25 at 12 29 00 AM](https://user-images.githubusercontent.com/31748545/197710758-313d2c92-d915-4a54-a4a7-d71e8d693a37.png)

**Comment by bliutech** [comment]
@burturt Maybe remove drop shadow for now? Figma does not have it in design and I think it will make styling a bit easier.

**Comment by burturt** [comment]
Oh wait I somehow interpreted 'animation' as 'drop shadow on hover' - well, I guess that's there for now

**Comment by bliutech** [comment]
I'll take a look in the PR once things are fixed but if it looks okay then maybe we can keep it. Sorry for unclear wording of specs.
