### ISSUE TITLE
LA CTF 2024 Sponsors

### ISSUE THREAD

**Issue by burturt** [uclaacm/lactf-website#65]
Confirmed sponsors for LA CTF 2024:

- [x] Sandia National Labs
- [x] OtterSec
- [x] LatticeWork
- [x] Google Cloud
- [x] Lockheed Martin
- [x] TryHackMe
- [x] TrailOfBits

When a sponsor has been added to the website and platform code, check it off. Keep this issue open to track which sponsors have been added and which still need to be added.

**Comment by epsteinmark** [comment]
Within sponsors, exists distinction between affiliate flag and infra flag, and flags are not mandatory. What are the use conditions for affiliate/infra/no flag? 

Maybe include which sponsors get what flag?

**Comment by burturt** [comment]
Affiliate flag means they are a [UCLA CS dept affiliate](https://www.cs.ucla.edu/affiliate-memberships/) and infra flag is a custom one just for google since they ask us specifically to put the text "infra sponsored by google", so Sandia should get the affiliate flag

**Comment by epsteinmark** [comment]
Since other sponsors merged, check off remaining sponsors on list.
